spring:
  application:
    name: stayhub
  servlet:
    multipart:
      max-file-size: 10MB # File upload limit, default 1MB not enough.
  jackson:
    default-property-inclusion: non_null
  datasource:
    url: jdbc:postgresql://${DATABASE_URL}:${DATABASE_PORT}/postgres
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    driver-class-name: org.postgresql.Driver
  flyway:
    enabled: true
    locations: classpath:db/migration
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    show-sql: false


stayhub:
  gcs:
    bucket: stayhub-bucket
  geocoding:
    key: ${GEOCODING_API_KEY}
  jwt:
    secret-key: ${JWT_SECRET_KEY}
